page_order:
  - programs
  - research
  - people

navbar_order:
  - programs
  - research
  - people
  - Resources
  - Methods
  - Professional Development
  - Syllabi
  - Certificates
  - Short Courses
  - Search
  - url: https://wakeforestid.com
    text: Home

dropdowns:
  Resources:
    - math
    - programming
  Methods:
    - epidemiology
    - diagnostics
  Professional Development:
    - scientific-pathways
    - scientific-writing
  Syllabi:
    - bio301-math-bio
    - bio340-id-ecology
    - bio390-research-tools
    - field-epidemiology
    - stewardship-infection-prevention
    - applied-id-epidemiology
    - outbreak-analytics
    - one-health-zoonoses
    - data-science-id
    - statistical-modeling-id
    - spatial-epidemiology
    - evolutionary-epidemiology
    - ideee-seminar
  Certificates:
    - certificate-id-modeling-analytics
    - certificate-quant-stewardship
    - certificate-global-health-data
  Short Courses:
    - shortcourse-intro-epi-biostats
    - shortcourse-outbreak-analytics
    - shortcourse-bayesian-stan
    - shortcourse-computation-math-biology
