page_order:
  - programs
  - research
  - people

navbar_order:
  - programs
  - research
  - people
  - Resources
  - Methods
  - Professional Development
  - Syllabi
  - Search
  - url: https://wakeforestid.com
    text: Home

dropdowns:
  Resources:
    - math
    - programming
  Methods:
    - epidemiology
    - diagnostics
  Professional Development:
    - scientific-pathways
    - scientific-writing
  Syllabi:
    - bio301-math-bio
    - bio340-id-ecology
    - bio390-research-tools
    - field-epidemiology
    - stewardship-infection-prevention
